ebitengine/oto

- player_openal.go
1) Adds source, buffer, and context cleanup - also checks to ensure that the device closed successfully, as alcCloseDevice returns ALC_TRUE/ALC_FALSE for successful/unsuccessful close
2) Removes unnecessary ALCdevice casting
3) Adds device name to this player in the case that there are multiple players playing to different devices (not currently possible but I would propose adding support for selecting from alcGetString(ALC_ALL_DEVICES_SPECIFIER);
> adjust openal cleanup

- player_openal.go
Hi, @hajimehoshi !
I sometimes faced panic by index out of bounds in player.Close function.
I don't see this problem in Linux, but only in OSX so far.
for the time being, I inserted checking length of p.bufs before its use.
It seems to help not to cause panic, but since I'm not sure the reason of index out of bounds occurs, i'm not sure this is applicable correction.
I'm very happy if you give some comment!
> openal: avoid possibility of panic by index out of bounds at player.Close

- player_android.go
Remove a comment that may not be necessary anymore because of fix #27.
I'm so sorry to say that I forgot to do this at #28 ...
> android: remove outdated comments

- driver_android.go
- driver_js.go
- driver_linux.go
- driver_openal.go
- driver_windows.go
- player.go
`bytesPerSample` is confusing since this is ambiguous: this might mean the total bytes in all the channels of one sample, or the bytes in one channel of one sample.
I suggest to rename this to `bitDepthInBytes` to avoid confusion. `bitDepthInBytes` is the bytes in one channel of one sample.
@faiface , @Noofbiz Please take a look just in case.
> Rename bytesPerSample -> bitDepthInBytes

- context.go
- example/main.go
- internal/mux/mux.go
- internal/mux/mux_test.go
- player.go
This implements #47
CC @faiface @Noofbiz 
I'll brush up, add tests and then would like to ask you to review.
EDIT: What I did in this change is:
* Add `Context`. That has a `driverWriter` to write bytes to the driver, and a `Mux` that reads multiplexed bytes from multiple sources. When a `Context` is created, run a goroutine to execute the loop of `io.Copy(driverWriter, Mux)`.
* Modify `Player` that has a reader and a writer from `io.Pipe`. The writer accepts the Player's user input and the reader is used at `mux`.
* Add `Mux` that multiplexes bytes from multiple sources (Player's reader in this case). This is in a separated internal package with tests. `Mux` also manages registration and de-registiration of the sources.
* Add `example/main.go` to test multiple players.
> Implement Context/Player for multiple playback sources

- context.go
Works on Windows 😃. Not sure about the other platforms.
Related to #47
> Allow context reuse after close

- driver_openal.go
Will allow for correct device names. Should not affect functionality.
Three important excepts from OpenAL's documentation:
1. `alGetString` does not support the parameters currently passed to it:
```
alGetString
Description
This function retrieves an OpenAL string property.
const ALchar * alGetString(
ALenum param
);
Parameters
param The property to be returned
AL_VENDOR
AL_VERSION
AL_RENDERER
AL_EXTENSIONS 
```
2. `alcGetString` supports what we're trying to use `alGetString` to do:
```
To get the default device name, pass in NULL and
ALC_DEFAULT_DEVICE_SPECIFIER . 
```
3. `alcOpenDevice` was handling this error case correctly, silently. Since the return value from `alGetString` is `Null`, `alcOpenDevice` was functioning as expected, opening the default device, though not through the …
> Bugfix, use alcGetString instead of alGetString

- driver_linux.go
On linux, `example/main.go` produces noticeably different output depending on the `bitDepthInBytes`. Executing `go run example/main.go -bitdepthinbytes=1` produces choppy audio, while `2` produces the expected sounds.
As best I can tell, this appears to be because `main.go` prepares an unsigned byte sample, while the format sent alsa is `SND_PCM_FORMAT_S8`. Changing this value to `SND_PCM_FORMAT_U8` makes the example behave as expected for `-bitdepthinbytes=1`.
I think this is a potentially breaking change, as someone who only targets linux might have realized this behaviour and written their code to account for it. But, I also think a breaking change would be justified here, as it brings the linux functionality to parity with the other platforms (and it's also pretty low impact since its …
> Use unsigned byte format on linux for compatability with other platforms

- internal/mux/mux.go
When using contexts with a bit depth of 1, there are audible pops ate the beginning and end of sounds when nothing else is playing. This fixes that by "zero-ing" the array to the `0` used later on to represent no sound, `128`.
> Output the offset value when in 1 bit depth

- driver_android.go
This change uses the FLAG_LOW_LATENCY flag on Android if it is available, and falls back to the previous way if not. 
The only downside I see is that in low latency mode the phone may skip some processing. On my phone the audio is noticeably louder in the low latency mode for some reason. But the latency was too high for me, so this is nevertheless preferable. It's up to you though.
> android: Added code path for low latency audio if available

- driver_windows.go
Reuse the allocated temp buffer by just setting its length to zero, instead of assigning it to nil. Produces less garbage.
> windows: do not reallocate temp buffer every time

- driver_windows.go
- winmm_windows.go
https://docs.microsoft.com/en-us/previous-versions/dd743856(v=vs.85)#remarks
Calling `waveOutReset` explicitly before `waveOutClose` to handle cases where the user calls `Close()` before the buffers are finished.
> Prevent Invalid Access Exceptions on Windows

- driver_windows.go
On 64-bit systems this distinction does not matter; on WINE things oddly work
either way (it is in theory possible for a caller to support both, as these
two differ only in how they return, not in how they pass arguments).
Fixes crash on Windows 7 x86.
Fixes #158.
> Use a `__stdcall` callback, not a `__cdecl` one, for waveOutOpen.

- driver.go
As I understand it, the v2 oto API no longer provides a facility to close contexts, and it also no longer needs contexts to be closed. This just drops a comment that references closing contexts.
> doc: remove language about closing contexts

- README.md
I noticed that Oto uses CGO, but we haven't mentioned it anywhere in the README, so this is a small update to add a mention about that.
> Mention C/C++ compiler requirement in README

- README.md
Now that https://github.com/hajimehoshi/oto/issues/172 is looking good and 19c3101d30142518729150dc41b54752776b14f8 is there we can update the docs.
This should probably be merged along with a new release.
> Docs: Use io.Seeker instead of Reset in docs

- internal/mux/mux.go
We cannot expect what would happen in an external function call, and this might block unexpectedly. Actually this causes stutters.
This changes fixes this issue by not locking when calling an external interface function Read.
Closes #188
> internal/mux: bug fix: unlock when calling an external function

- README.md
Hi
a small readme update:
SInce I'm using Fedora I've noticed that the package name is diffrent than ubuntu/debian's one.
> readme: add setup instruction for redhat-based linux distros

- README.md
This is just a little tweak to clarify that Cgo isn't required for Windows/MacOS. As currently written it could read as 'not required', but also as 'not allowed'.
> Clarify Cgo in readme

- internal/mux/mux.go
This way different player instances can re-use memory buffers. This helps keeping the allocation rate low and reduces gc.
Sharing is fine under the assumption that after a short while all buffers are at least as large as we currently need them to be. If we get a buffer from the pool that is smaller than the current required buffer size, we'll alloc a bigger buffer and return that one into the pool. Next time, we'll probably get a buffer of the correct size.
We now also share the p.buf buffer between players. If a player is stopped or has reached eof, the buffer is put back into the pool.
In total, this change helps to reduce the allocation rate (and in turn garbage pressure) when playing a lot of short lived sound effects, and it does not hinder long running playback.
> Optimize memory re-use by using one buffer pool for all players.
